/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-04-26 02:47:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test5_005fjson_005fmovie_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../js/jquery-3.6.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#btnOk\").on(\"click\", function() {\r\n");
      out.write("			/*\r\n");
      out.write("			영화진흥위원회 오픈API 를 활용하여 영화 정보 JSON 데이터 처리\r\n");
      out.write("			https://www.kobis.or.kr/kobisopenapi/homepg/main/main.do\r\n");
      out.write("			-------------------------------------------------------------\r\n");
      out.write("			일별 박스오피스 목록 조회 후 테이블에 표시\r\n");
      out.write("			https://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do?serviceId=searchDailyBoxOffice\r\n");
      out.write("			=> 지정된 요청 파라미터 형식에 맞게 URL 을 수정해야함\r\n");
      out.write("			\r\n");
      out.write("			샘플 API 요청 주소(단, 대상 조회일자(targetDt)는 어제(2023년 4월 25일로 변경))\r\n");
      out.write("			http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20230425\r\n");
      out.write("			*/\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"GET\",\r\n");
      out.write("				url: \"http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20230425\",\r\n");
      out.write("				dataType: \"json\", // 응답 데이터가 JSON 객체로 전달되도록 \"json\" 타입 지정\r\n");
      out.write("				success: function(data) { // 요청 성공 시\r\n");
      out.write("					// 임시) #resultArea 영역에 응답 데이터 출력(문자열로 변환 필요)\r\n");
      out.write("// 					$(\"#resultArea\").html(JSON.stringify(data));		\r\n");
      out.write("					// ----------------------------------------------------------------------\r\n");
      out.write("					// 응답 데이터(박스오피스 목록) 객체(data)로부터 박스오피스 정보 추출하기\r\n");
      out.write("					// => 전체 데이터가 하나의 객체({})로 묶여 있음\r\n");
      out.write("					// 1. 박스오피스 전체 데이터가 저장된 \"boxOfficeResult\" 객체 추출\r\n");
      out.write("					let boxOfficeResult = data.boxOfficeResult;\r\n");
      out.write("// 					$(\"#resultArea\").html(JSON.stringify(boxOfficeResult));		\r\n");
      out.write("\r\n");
      out.write("					// 2. 박스오피스 타입(boxofficeType)과 조회날짜(showRange) 추출\r\n");
      out.write("					// => 1번에서 추출한 boxOfficeResult 객체를 통해 접근\r\n");
      out.write("					let boxOfficeType = boxOfficeResult.boxofficeType;\r\n");
      out.write("					let showRange = boxOfficeResult.showRange;\r\n");
      out.write("// 					$(\"#resultArea\").html(JSON.stringify(boxOfficeType + \", \" + showRange));\r\n");
      out.write("					// 두 데이터는 객체가 아니므로 별도의 변환 없이도 사용 가능\r\n");
      out.write("// 					$(\"#resultArea\").html(boxOfficeType + \", \" + showRange);	\r\n");
      out.write("					\r\n");
      out.write("					// 3. 일별 박스오피스 목록(dailyBoxOfficeList) 추출\r\n");
      out.write("					// => 복수개의 영화정보 객체{}가 dailyBoxOfficeList 배열[] 로 관리됨\r\n");
      out.write("					// => 단, 배열 내의 데이터가 객체이므로 출력 시 변환 필요함\r\n");
      out.write("					let dailyBoxOfficeList = boxOfficeResult.dailyBoxOfficeList;\r\n");
      out.write("// 					$(\"#resultArea\").html(JSON.stringify(dailyBoxOfficeList));	\r\n");
      out.write("\r\n");
      out.write("					// 4. 추출된 박스오피스 목록(배열)을 반복문을 통해 차례대로 접근하여\r\n");
      out.write("					//    순위(rank), 제목(movieNm), 개봉일(openDt), 누적관객수(audiAcc) 추출 후 출력\r\n");
      out.write("					for(let movie of dailyBoxOfficeList) {\r\n");
      out.write("						$(\"#resultArea > table\").append(\r\n");
      out.write("							\"<tr>\"\r\n");
      out.write("							+ \"<td>\" + movie.rank + \"</td>\"\r\n");
      out.write("							+ \"<td>\" + movie.movieNm + \"</td>\"\r\n");
      out.write("							+ \"<td>\" + movie.openDt + \"</td>\"\r\n");
      out.write("							+ \"<td>\" + movie.audiAcc + \"</td>\"\r\n");
      out.write("							+ \"</tr>\"\r\n");
      out.write("						);\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				error: function() { // 요청 실패 시\r\n");
      out.write("					$(\"#resultArea\").html(\"<h1>요청 실패!</h1>\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>test5_json_movie_list.jsp - 일별 박스오피스</h1>\r\n");
      out.write("	<input type=\"button\" value=\"일별 박스오피스 조회\" id=\"btnOk\">\r\n");
      out.write("	| <input type=\"date\" id=\"date\"><input type=\"button\" value=\"일별 박스오피스 조회(날짜선택)\" id=\"btnOk\">\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div id=\"resultArea\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th width=\"80\">현재순위</th>\r\n");
      out.write("				<th width=\"400\">영화명</th>\r\n");
      out.write("				<th width=\"150\">개봉일</th>\r\n");
      out.write("				<th width=\"100\">누적관객수</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
