/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-04-26 01:32:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test3_005fjson_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../js/jquery-3.6.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#btnOk\").on(\"click\", function() {\r\n");
      out.write("			// =====================================================\r\n");
      out.write("			// test3_json_data.txt 파일을 AJAX 를 통해 요청\r\n");
      out.write("			// - 응답 데이터 형식을 \"text\" 로 지정하여 text 형식 데이터 요청\r\n");
      out.write("			// - AJAX 요청 성공 시 자동으로 호출되는 콜백 함수를 success: 속성에 기술\r\n");
      out.write("			//   (또는 $.ajax() 함수 외부에 done() 함수를 연결하여 콜백 처리도 가능)\r\n");
      out.write("			//   (=> 단, success: 와 done() 은 기술 위치가 다름)\r\n");
      out.write("// 			$.ajax({\r\n");
      out.write("// 				type: \"GET\",\r\n");
      out.write("// 				url: \"test3_json_data.txt\",\r\n");
      out.write("// 				dataType: \"text\", // 응답 데이터가 일반 텍스트로 전달되도록 \"text\" 타입 지정\r\n");
      out.write("// 				success: function(msg) { // 요청 성공 시\r\n");
      out.write("// 					alert(\"요청 성공! - \" + msg);\r\n");
      out.write("// 				},\r\n");
      out.write("// 				error: function() { // 요청 실패 시\r\n");
      out.write("// 					alert(\"요청 실패!\");\r\n");
      out.write("// 				}\r\n");
      out.write("// 			});\r\n");
      out.write("			\r\n");
      out.write("			// 위와 동일한 작업 결과를 가지나 성공/실패 처리 형태가 다른 문법\r\n");
      out.write("			// => done(), fail() 함수를 사용하며, done() 은 success 와 같지만 우선순위가 낮음\r\n");
      out.write("// 			$.ajax({\r\n");
      out.write("// 				type: \"GET\",\r\n");
      out.write("// 				url: \"test3_json_data.txt\",\r\n");
      out.write("// 				dataType: \"text\" // 응답 데이터가 일반 텍스트로 전달되도록 \"text\" 타입 지정\r\n");
      out.write("// 			})\r\n");
      out.write("// 			.done(function(msg) {\r\n");
      out.write("// 				alert(\"요청 성공! - \" + msg);\r\n");
      out.write("// 			})\r\n");
      out.write("// 			.fail(function() {\r\n");
      out.write("// 				alert(\"요청 실패!\");\r\n");
      out.write("// 			});\r\n");
      out.write("			// ============================================================================\r\n");
      out.write("			// test3_json_data.txt 파일 내용 요청 시 응답 형식을 JSON 형식으로 지정하여\r\n");
      out.write("			// JSON 객체로 데이터가 응답되도록 할 수 있다! \r\n");
      out.write("			// => 즉시, JSON 객체로 처리 가능\r\n");
      out.write("			// => 단, 잘못된 JSON 형태의 데이터도 일단 JSON 객체로 전달받음(처리 과정에서 오류 발생)\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"GET\",\r\n");
      out.write("				url: \"test3_json_data.txt\",\r\n");
      out.write("				dataType: \"json\" // 응답 데이터가 JSON 객체 형태로 전달되도록 \"json\" 타입 지정\r\n");
      out.write("			})\r\n");
      out.write("			.done(function(data) {\r\n");
      out.write("// 				alert(\"요청 성공! - \" + data); // JSON 객체 형태이므로 그대로 사용 불가(object 타입)\r\n");
      out.write("				// ------------------------------------------------------------------\r\n");
      out.write("				// 만약, 전달받은 JSON 객체를 문자열 형식으로 변환할 경우\r\n");
      out.write("				// 자바스크립트 내장 객체인 JSON 을 사용하여\r\n");
      out.write("				// JSON.stringify() 형식으로 메서드를 호출하여 변환 가능(파라미터 : JSON 객체)\r\n");
      out.write("// 				$(\"#resultArea\").html(JSON.stringify(data)); // {\"id\":\"admin\",\"name\":\"관리자\",\"age\":0}\r\n");
      out.write("// 				$(\"#resultArea\").append(\"<br>타입 : \" + typeof(JSON.stringify(data))); // string\r\n");
      out.write("				// ------------------------------------------------------------------\r\n");
      out.write("				// JSON 데이터를 객체 형태로 접근하여 테이블에 해당 데이터 출력\r\n");
      out.write("				// JSON 데이터를 표시할 테이블 생성\r\n");
      out.write("				$(\"#resultArea\").html(\r\n");
      out.write("					\"<table border='1'><tr><th colspan='3'>JSON 데이터 파싱 결과</th></tr>\"\r\n");
      out.write("					+ \"<tr><th>아이디</th><th>이름</th><th>나이</th></tr></table>\"\r\n");
      out.write("				);\r\n");
      out.write("				\r\n");
      out.write("				// JSON 데이터가 중괄호{} 로 감싸져 있을 경우 객체 데이터로 취급되고\r\n");
      out.write("				// 해당 객체 내의 속성들이 변수 역할을 수행하므로\r\n");
      out.write("				// AJAX 를 통해 리턴받은 객체가 저장된 변수 data 를 통해 id, name, age 속성에 접근\r\n");
      out.write("				// => 객체명.속성명 형태로 접근(ex. data.id)\r\n");
      out.write("				// #resultArea 영역의 <table> 태그 내에 마지막 요소로 1개 행 삽입\r\n");
      out.write("				$(\"#resultArea > table\").append(\r\n");
      out.write("					\"<tr>\"\r\n");
      out.write("					+ \"<td>\" + data.id + \"</td>\"\r\n");
      out.write("					+ \"<td>\" + data.name + \"</td>\"\r\n");
      out.write("					+ \"<td>\" + data.age + \"</td>\"\r\n");
      out.write("					+ \"</tr>\"\r\n");
      out.write("				);\r\n");
      out.write("			})\r\n");
      out.write("			.fail(function() {\r\n");
      out.write("				alert(\"요청 실패!\");\r\n");
      out.write("			});\r\n");
      out.write("			// ==========================================================================\r\n");
      out.write("			// test3_json_data.txt 파일 내용 요청 시 응답 형식을 JSON 형식으로 지정하여\r\n");
      out.write("			// JSON 객체로 데이터가 응답되도록 할 수 있다! \r\n");
      out.write("			// => 즉시, JSON 객체로 처리 가능\r\n");
      out.write("			// => 단, 잘못된 JSON 형태의 데이터도 일단 JSON 객체로 전달받음(처리 과정에서 오류 발생)\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"GET\",\r\n");
      out.write("				url: \"test3_json_data2.json\",\r\n");
      out.write("				dataType: \"json\" // 응답 데이터가 JSON 객체 형태로 전달되도록 \"json\" 타입 지정\r\n");
      out.write("			})\r\n");
      out.write("			.done(function(data) {\r\n");
      out.write("// 				alert(\"요청 성공! - \" + data); // JSON 객체 형태이므로 그대로 사용 불가(object 타입)\r\n");
      out.write("				// ------------------------------------------------------------------\r\n");
      out.write("				// 만약, 전달받은 JSON 객체를 문자열 형식으로 변환할 경우\r\n");
      out.write("				// 자바스크립트 내장 객체인 JSON 을 사용하여\r\n");
      out.write("				// JSON.stringify() 형식으로 메서드를 호출하여 변환 가능(파라미터 : JSON 객체)\r\n");
      out.write("// 				$(\"#resultArea\").html(JSON.stringify(data)); // {\"id\":\"admin\",\"name\":\"관리자\",\"age\":0}\r\n");
      out.write("// 				$(\"#resultArea\").append(\"<br>타입 : \" + typeof(JSON.stringify(data))); // string\r\n");
      out.write("				// ------------------------------------------------------------------\r\n");
      out.write("				// JSON 데이터를 객체 형태로 접근하여 테이블에 해당 데이터 출력\r\n");
      out.write("				// JSON 데이터를 표시할 테이블 생성\r\n");
      out.write("				$(\"#resultArea2\").html(\r\n");
      out.write("					\"<table border='1'><tr><th colspan='4'>JSON 데이터 파싱 결과</th></tr>\"\r\n");
      out.write("					+ \"<tr><th>아이디</th><th>이름</th><th>나이</th><th>주소</th></tr></table>\"\r\n");
      out.write("				);\r\n");
      out.write("				\r\n");
      out.write("				// JSON 데이터에서 객체 내에 또 다른 객체가 포함되어 있을 경우\r\n");
      out.write("				// 객체명1.객체명2.속성명 형태로 접근\r\n");
      out.write("				$(\"#resultArea2 > table\").append(\r\n");
      out.write("					\"<tr>\"\r\n");
      out.write("					+ \"<td>\" + data.id + \"</td>\"\r\n");
      out.write("					+ \"<td>\" + data.name + \"</td>\"\r\n");
      out.write("					+ \"<td>\" + data.age + \"</td>\"\r\n");
      out.write("// 					+ \"<td>\" + data.address + \"</td>\" // address 객체 내에 객체가 또 있으므로 object 출력됨\r\n");
      out.write("					+ \"<td>\" + data.address.address1 + \" \" + data.address.address2 + \"</td>\"\r\n");
      out.write("					+ \"</tr>\"\r\n");
      out.write("				);\r\n");
      out.write("			})\r\n");
      out.write("			.fail(function() {\r\n");
      out.write("				alert(\"요청 실패!\");\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>test3_json.jsp - AJAX</h1>\r\n");
      out.write("	<input type=\"button\" value=\"JSON 데이터 파싱\" id=\"btnOk\">\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div id=\"resultArea\"></div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div id=\"resultArea2\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
