/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-13 03:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1675146893323L));
    _jspx_dependants.put("jar:file:/D:/Shared/JSP/workspace_JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MVC_Board/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/Shared/JSP/workspace_JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MVC_Board/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>W3.CSS Template</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/lib/w3-theme-red.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Side Navigation -->\r\n");
      out.write("<nav class=\"w3-sidebar w3-bar-block w3-card w3-animate-left w3-center\" style=\"display:none\" id=\"mySidebar\">\r\n");
      out.write("  <h1 class=\"w3-xxxlarge w3-text-theme\">Side Navigation</h1>\r\n");
      out.write("  <button class=\"w3-bar-item w3-button\" onclick=\"w3_close()\">Close <i class=\"fa fa-remove\"></i></button>\r\n");
      out.write("  <a href=\"BoardWriteForm.bo\" class=\"w3-bar-item w3-button\">글쓰기</a>\r\n");
      out.write("  <a href=\"BoardList.bo\" class=\"w3-bar-item w3-button\">글목록</a>\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button\">Link 3</a>\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button\">Link 4</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"w3-container w3-theme w3-padding\" id=\"myHeader\">\r\n");
      out.write("  <i onclick=\"w3_open()\" class=\"fa fa-bars w3-xlarge w3-button w3-theme\"></i> \r\n");
      out.write("  <div class=\"w3-center\">\r\n");
      out.write("  <h4>BEAUTIFUL RESPONSIVE WEB SITES</h4>\r\n");
      out.write("  <h1 class=\"w3-xxxlarge w3-animate-bottom\">BUILT WITH W3.CSS</h1>\r\n");
      out.write("    <div class=\"w3-padding-32\">\r\n");
      out.write("      <button class=\"w3-btn w3-xlarge w3-theme-dark w3-hover-red\" onclick=\"document.getElementById('id01').style.display='block'\" style=\"font-weight:900;\">LEARN W3.CSS</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"id01\" class=\"w3-modal\">\r\n");
      out.write("    <div class=\"w3-modal-content w3-card-4 w3-animate-top\">\r\n");
      out.write("      <header class=\"w3-container w3-theme\"> \r\n");
      out.write("        <span onclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("        class=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("        <h4>Oh snap! We just showed you a modal..</h4>\r\n");
      out.write("        <h5>Because we can <i class=\"fa fa-smile-o\"></i></h5>\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\"w3-padding\">\r\n");
      out.write("        <p>Cool huh? Ok, enough teasing around..</p>\r\n");
      out.write("        <p>Go to our <a class=\"w3-btn\" href=\"/w3css/default.asp\">W3.CSS Tutorial</a> to learn more!</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <footer class=\"w3-container w3-theme\">\r\n");
      out.write("        <p>Modal footer</p>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row-padding w3-center w3-margin-top\">\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n");
      out.write("  <h3>기본 게시판</h3><br>\r\n");
      out.write("  <i class=\"fa fa-desktop w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n");
      out.write("  <p><b>최근 게시물 목록</b></p><br>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <table>\r\n");
      out.write("  	<tr>\r\n");
      out.write("  		<th style=\"max-width: 200px\">제목</th>\r\n");
      out.write("  		<th style=\"max-width: 80px\">작성자</th>\r\n");
      out.write("  	</tr>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n");
      out.write("  <h3>Standard CSS</h3><br>\r\n");
      out.write("  <i class=\"fa fa-css3 w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n");
      out.write("  <p>Standard CSS only</p>\r\n");
      out.write("  <p>Easy to learn</p>\r\n");
      out.write("  <p>No need for jQuery</p>\r\n");
      out.write("  <p>No JavaScript library</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("  <div class=\"w3-card w3-container\" style=\"min-height:460px\">\r\n");
      out.write("  <h3>Design</h3><br>\r\n");
      out.write("  <i class=\"fa fa-diamond w3-margin-bottom w3-text-theme\" style=\"font-size:120px\"></i>\r\n");
      out.write("  <p>Paper like design</p>\r\n");
      out.write("  <p>Bold colors and shadows</p>\r\n");
      out.write("  <p>Equal across platforms</p>\r\n");
      out.write("  <p>Equal across devices</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <h2>Color Classes</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row\">\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-red\"><p>Red</p></div>\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-blue\"><p>Blue</p></div>\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-blue-grey\"><p>Blue Grey</p></div>\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-teal\"><p>Teal</p></div>\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-yellow\"><p>Yellow</p></div>\r\n");
      out.write("  <div class=\"w3-col w3-container m2 w3-orange\"><p>Orange</p></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <h2>Built-In Responsiveness</h2>\r\n");
      out.write("  <p class=\"w3-large\">Resize the page to see the effect!</p>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row w3-border\">\r\n");
      out.write("  <div class=\"w3-half w3-container w3-blue w3-border\">\r\n");
      out.write("    <h5>w3-half</h5>  \r\n");
      out.write("    <p>The w3-half class uses half (50%) of the screen window.</p>\r\n");
      out.write("    <p>On small screens (max 600 pixels) it automatically resizes to full screen width.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-half w3-container\">\r\n");
      out.write("    <h5>w3-half</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row w3-border\">\r\n");
      out.write("  <div class=\"w3-third w3-container w3-green\">\r\n");
      out.write("    <h5>w3-third</h5>  \r\n");
      out.write("    <p>The w3-third class uses one third (33.33%) of the screen window.</p>\r\n");
      out.write("    <p>On small screens (max 600 pixels) it automatically resizes to full screen width.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-third w3-container\">\r\n");
      out.write("    <h5>w3-third</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-third w3-container\">\r\n");
      out.write("    <h5>w3-third</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row w3-border\">\r\n");
      out.write("  <div class=\"w3-quarter w3-container w3-red\">\r\n");
      out.write("    <h5>w3-quarter</h5>  \r\n");
      out.write("    <p>The w3-quarter class uses one quarter (25%) of the screen window.</p>\r\n");
      out.write("    <p>On small screens (max 600 pixels) it automatically resizes to full screen width.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-quarter w3-container\">\r\n");
      out.write("    <h5>w3-quarter</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-quarter w3-container\">\r\n");
      out.write("    <h5>w3-quarter</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-quarter w3-container\">\r\n");
      out.write("    <h5>w3-quarter</h5>  \r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write("     \r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <h2>Containers</h2>\r\n");
      out.write("  <p>Use containers to create headers, sections and footers.</p>\r\n");
      out.write("</div>   \r\n");
      out.write("\r\n");
      out.write("<header class=\"w3-container w3-blue-grey\">\r\n");
      out.write("  <h2>Header</h2>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-padding w3-white w3-display-container\">\r\n");
      out.write("  <span onclick=\"this.parentElement.style.display='none'\" class=\"w3-button w3-display-topright\"><i class=\"fa fa-remove\"></i></span>\r\n");
      out.write("  <h2>London</h2>\r\n");
      out.write("  <p>London is the capital city of England. It is the most populous city in the United Kingdom,\r\n");
      out.write("  with a metropolitan area of over 13 million inhabitants.</p>\r\n");
      out.write("  <p>Standing on the River Thames, London has been a major settlement for two millennia,\r\n");
      out.write("  its history going back to its founding by the Romans, who named it Londinium.</p>\r\n");
      out.write("  <p>By the way, you can add a close icon to all containers if you want the ability to hide them. Look to your right!</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"w3-container w3-blue-grey\">\r\n");
      out.write("  <h5>Footer</h5>\r\n");
      out.write("  <p class=\"w3-opacity\">Footer information goes here</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <h2>Color Themes</h2>\r\n");
      out.write("  <p>The color themes have been designed to work harmoniously with each other.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row-padding\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-half\">\r\n");
      out.write("<div class=\"w3-card white\">\r\n");
      out.write("  <div class=\"w3-container w3-indigo\">\r\n");
      out.write("    <h3>Theme Indigo</h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("  <h3 class=\"w3-text-indigo\">Movies 2014</h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <ul class=\"w3-ul w3-border-top\">\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>Frozen</h3>\r\n");
      out.write("      <p>The response to the animations was ridiculous</p>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>The Fault in Our Stars</h3>\r\n");
      out.write("      <p>Touching, gripping and genuinely well made</p>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>The Avengers</h3>\r\n");
      out.write("      <p>A huge success for Marvel and Disney</p>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div class=\"w3-container w3-indigo w3-large\"><span class=\"w3-right\">Next</span></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-half\">\r\n");
      out.write("<div class=\"w3-card white\">\r\n");
      out.write("  <div class=\"w3-container w3-theme\">\r\n");
      out.write("    <h3>Theme</h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("  <h3 class=\"w3-text-theme\">Movies 2014</h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <ul class=\"w3-ul w3-border-top\">\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>Frozen</h3>\r\n");
      out.write("      <p>The response to the animations was ridiculous</p>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>The Fault in Our Stars</h3>\r\n");
      out.write("      <p>Touching, gripping and genuinely well made</p>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <h3>The Avengers</h3>\r\n");
      out.write("      <p>A huge success for Marvel and Disney</p>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div class=\"w3-container w3-theme w3-large\"><span class=\"w3-right\">Next</span></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-container w3-center\">\r\n");
      out.write("  <hr>\r\n");
      out.write("  <h3>Paper-like Cards with Shadows</h3>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row-padding\"> \r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("<div class=\"w3-card\">\r\n");
      out.write("  <img src=\"/w3images/car.jpg\" alt=\"Car\" style=\"width:100%\">\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("  <p>w3-card</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("<div class=\"w3-card-4\">\r\n");
      out.write("  <img src=\"/w3images/car.jpg\" alt=\"Car\" style=\"width:100%\">\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("  <p>w3-card-4</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-third\">\r\n");
      out.write("<div class=\"w3-card-4\">\r\n");
      out.write("  <img src=\"/w3images/car.jpg\" alt=\"Car\" style=\"width:100%\">\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("  <p>w3-card-4</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("  <hr>\r\n");
      out.write("  <div class=\"w3-center\">\r\n");
      out.write("    <h2>Tables</h2>\r\n");
      out.write("    <p w3-class=\"w3-large\">Don't worry. W3.CSS takes care of your tables.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("<div class=\"w3-responsive w3-card-4\">\r\n");
      out.write("<table class=\"w3-table w3-striped w3-bordered\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr class=\"w3-theme\">\r\n");
      out.write("  <th>First Name</th>\r\n");
      out.write("  <th>Last Name</th>\r\n");
      out.write("  <th>Points</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("  <td>Jill</td>\r\n");
      out.write("  <td>Smith</td>\r\n");
      out.write("  <td>50</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr class=\"w3-white\">\r\n");
      out.write("  <td>Eve</td>\r\n");
      out.write("  <td>Jackson</td>\r\n");
      out.write("  <td>94</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("  <td>Adam</td>\r\n");
      out.write("  <td>Johnson</td>\r\n");
      out.write("  <td>67</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2 class=\"w3-center\">Forms and Lists</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-row-padding\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-half\">\r\n");
      out.write("<form class=\"w3-container w3-card-4\">\r\n");
      out.write("  <h2>Input Form</h2>\r\n");
      out.write("  <div class=\"w3-section\">      \r\n");
      out.write("    <input class=\"w3-input\" type=\"text\" required>\r\n");
      out.write("    <label>Name</label>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-section\">      \r\n");
      out.write("    <input class=\"w3-input\" type=\"text\" required>\r\n");
      out.write("    <label>Email</label>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w3-section\">      \r\n");
      out.write("    <input class=\"w3-input\" type=\"text\" required>\r\n");
      out.write("    <label>Subject</label>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-row\">\r\n");
      out.write("  <div class=\"w3-half\">\r\n");
      out.write("    <input id=\"milk\" class=\"w3-check\" type=\"checkbox\" checked=\"checked\">\r\n");
      out.write("    <label>Milk</label>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input id=\"sugar\" class=\"w3-check\" type=\"checkbox\">\r\n");
      out.write("    <label>Sugar</label>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input id=\"lemon\" class=\"w3-check\" type=\"checkbox\" disabled>\r\n");
      out.write("    <label>Lemon (Disabled)</label>\r\n");
      out.write("    <br><br>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-half\">\r\n");
      out.write("    <input id=\"male\" class=\"w3-radio\" type=\"radio\" name=\"gender\" value=\"male\" checked>\r\n");
      out.write("    <label>Male</label>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input id=\"female\" class=\"w3-radio\" type=\"radio\" name=\"gender\" value=\"female\">\r\n");
      out.write("    <label>Female</label>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input id=\"unknown\" class=\"w3-radio\" type=\"radio\" name=\"gender\" value=\"\" disabled>\r\n");
      out.write("    <label> Don't know (Disabled)</label>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"w3-half\">\r\n");
      out.write("<div class=\"w3-card-4 w3-container\">\r\n");
      out.write("<h2>Lists</h2>\r\n");
      out.write("<ul class=\"w3-ul w3-margin-bottom\">\r\n");
      out.write("  <li>Jill</li>\r\n");
      out.write("  <li>Eve</li>\r\n");
      out.write("  <li>Adam</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<br>\r\n");
      out.write("<ul class=\"w3-ul w3-border w3-hoverable\">\r\n");
      out.write("  <li class=\"w3-theme\">Jill</li>\r\n");
      out.write("  <li>Eve</li>\r\n");
      out.write("  <li>Adam</li>\r\n");
      out.write("  <li>Steve</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<br>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"w3-center\">Progress Bars</h2>\r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-light-grey\">\r\n");
      out.write("  <div id=\"myBar\" class=\"w3-container w3-padding w3-theme\" style=\"width:1%\">0</div>\r\n");
      out.write("</div><br>\r\n");
      out.write("\r\n");
      out.write("<button class=\"w3-btn w3-theme\" onclick=\"move()\">Click Me</button> \r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"w3-center\">Slideshows</h2>\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:800px;position:relative\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"mySlides w3-animate-opacity\" src=\"/w3images/snow.jpg\" style=\"width:100%\">\r\n");
      out.write("<img class=\"mySlides w3-animate-opacity\" src=\"/w3images/lights.jpg\" style=\"width:100%\">\r\n");
      out.write("<img class=\"mySlides w3-animate-opacity\" src=\"/w3images/mountains.jpg\" style=\"width:100%\">\r\n");
      out.write("<img class=\"mySlides w3-animate-opacity\" src=\"/w3images/forest.jpg\" style=\"width:100%\">\r\n");
      out.write("\r\n");
      out.write("<a class=\"w3-button w3-hover-dark-grey\" style=\"position:absolute;top:45%;left:0;\" onclick=\"plusDivs(-1)\">&#10094;</a>\r\n");
      out.write("<a class=\"w3-button w3-hover-dark-grey\" style=\"position:absolute;top:45%;right:0;\" onclick=\"plusDivs(+1)\">&#10095;</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("<hr>\r\n");
      out.write("<h2 class=\"w3-center\">Navigation</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-bar w3-theme\">\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button w3-padding-16\">Home</a>\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button w3-padding-16\">Link 1</a>\r\n");
      out.write("  <div class=\"w3-dropdown-hover\">\r\n");
      out.write("    <button class=\"w3-button w3-padding-16\">\r\n");
      out.write("      Dropdown <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"w3-dropdown-content w3-card-4 w3-bar-block\">\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 1</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 2</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 3</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"w3-center\">Accordions</h2>\r\n");
      out.write("<button onclick=\"myAccFunc('Demo1')\" class=\"w3-padding-16 w3-theme w3-button w3-block w3-left-align\">Open Section 1</button>\r\n");
      out.write("<div id=\"Demo1\" class=\"w3-hide\">\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<button onclick=\"myAccFunc('Demo2')\" class=\"w3-padding-16 w3-theme w3-button w3-block w3-left-align\">Open Section 2</button>\r\n");
      out.write("<div id=\"Demo2\" class=\"w3-hide\">\r\n");
      out.write("  <a href=\"#\" class=\"w3-button w3-block w3-left-align\">Link 1</a>\r\n");
      out.write("  <a href=\"#\" class=\"w3-button w3-block w3-left-align\">Link 2</a>\r\n");
      out.write("  <a href=\"#\" class=\"w3-button w3-block w3-left-align\">Link 3</a>\r\n");
      out.write("</div>\r\n");
      out.write("<button onclick=\"myAccFunc('Demo3')\" class=\"w3-padding-16 w3-theme w3-button w3-block w3-left-align\">Open Section 3</button>\r\n");
      out.write("<div id=\"Demo3\" class=\"w3-hide w3-black\">\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("    <p>Accordion with Images:</p>\r\n");
      out.write("    <img src=\"/w3images/snow.jpg\" style=\"width:30%;\" class=\"w3-animate-zoom\">\r\n");
      out.write("    <p>French Alps</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2 class=\"w3-center\">Tabs</h2>\r\n");
      out.write("<div class=\"w3-border\">\r\n");
      out.write("<div class=\"w3-bar w3-theme\">\r\n");
      out.write("  <button class=\"w3-bar-item w3-button testbtn w3-padding-16\" onclick=\"openCity(event,'London')\">London</button>\r\n");
      out.write("  <button class=\"w3-bar-item w3-button testbtn w3-padding-16\" onclick=\"openCity(event,'Paris')\">Paris</button>\r\n");
      out.write("  <button class=\"w3-bar-item w3-button testbtn w3-padding-16\" onclick=\"openCity(event,'Tokyo')\">Tokyo</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"London\" class=\"w3-container city w3-animate-opacity\">\r\n");
      out.write("  <h2>London</h2>\r\n");
      out.write("  <p>London is the capital city of England.</p>\r\n");
      out.write("  <p>It is the most populous city in the United Kingdom, with a metropolitan area of over 13 million inhabitants.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Paris\" class=\"w3-container city w3-animate-opacity\">\r\n");
      out.write("  <h2>Paris</h2>\r\n");
      out.write("  <p>Paris is the capital of France.</p> \r\n");
      out.write("  <p>The Paris area is one of the largest population centers in Europe, with more than 12 million inhabitants.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Tokyo\" class=\"w3-container city w3-animate-opacity\">\r\n");
      out.write("  <h2>Tokyo</h2>\r\n");
      out.write("  <p>Tokyo is the capital of Japan.</p>\r\n");
      out.write("  <p>It is the center of the Greater Tokyo Area, and the most populous metropolitan area in the world.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2 class=\"w3-center\">Buttons</h2>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <a class=\"w3-button w3-theme\">Button</a>\r\n");
      out.write("  <a class=\"w3-button w3-theme\">Button</a>\r\n");
      out.write("  <a class=\"w3-button w3-theme-d3 w3-disabled\">Button</a>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <a class=\"w3-button w3-circle w3-large w3-black\"><i class=\"fa fa-plus\"></i></a>\r\n");
      out.write("  <a class=\"w3-button w3-circle w3-large w3-theme\"><i class=\"fa fa-plus\"></i></a>  \r\n");
      out.write("  <a class=\"w3-button w3-circle w3-large w3-card-4\"><i class=\"fa fa-plus\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <div class=\"w3-dropdown-hover\">\r\n");
      out.write("    <button class=\"w3-button w3-theme\">Dropdown <i class=\"fa fa-caret-down\"></i></button>\r\n");
      out.write("    <div class=\"w3-dropdown-content w3-bar-block w3-border\">\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 1</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 2</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button\">Link 3</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"w3-center\">\r\n");
      out.write("  <h2>Pagination</h2>\r\n");
      out.write("  <!-- Pagination -->\r\n");
      out.write("  <div class=\"w3-center w3-padding-32\">\r\n");
      out.write("    <div class=\"w3-bar\">\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">&laquo;</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-theme w3-hover-theme\">1</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">2</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">3</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">4</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">5</a>\r\n");
      out.write("      <a href=\"#\" class=\"w3-bar-item w3-button w3-hover-theme\">&raquo;</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-container w3-theme-dark\">\r\n");
      out.write("  <h3>Footer</h3>\r\n");
      out.write("  <p>Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\">w3.css</a></p>\r\n");
      out.write("  <div style=\"position:relative;bottom:55px;\" class=\"w3-tooltip w3-right\">\r\n");
      out.write("    <span class=\"w3-text w3-theme w3-padding\">Go To Top</span>&nbsp;   \r\n");
      out.write("    <a class=\"w3-text-white\" href=\"#myHeader\"><span class=\"w3-xlarge\">\r\n");
      out.write("    <i class=\"fa fa-chevron-circle-up\"></i></span></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>Remember to check out our&nbsp;&nbsp;<a href=\"w3css_references.asp\" class=\"w3-btn w3-theme\" target=\"_blank\">W3.CSS Reference</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->\r\n");
      out.write("<script>\r\n");
      out.write("// Side navigation\r\n");
      out.write("function w3_open() {\r\n");
      out.write("  var x = document.getElementById(\"mySidebar\");\r\n");
      out.write("  x.style.width = \"100%\";\r\n");
      out.write("  x.style.fontSize = \"40px\";\r\n");
      out.write("  x.style.paddingTop = \"10%\";\r\n");
      out.write("  x.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function w3_close() {\r\n");
      out.write("  document.getElementById(\"mySidebar\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Tabs\r\n");
      out.write("function openCity(evt, cityName) {\r\n");
      out.write("  var i;\r\n");
      out.write("  var x = document.getElementsByClassName(\"city\");\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("  var activebtn = document.getElementsByClassName(\"testbtn\");\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    activebtn[i].className = activebtn[i].className.replace(\" w3-theme-dark\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("  document.getElementById(cityName).style.display = \"block\";\r\n");
      out.write("  evt.currentTarget.className += \" w3-theme-dark\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var mybtn = document.getElementsByClassName(\"testbtn\")[0];\r\n");
      out.write("mybtn.click();\r\n");
      out.write("\r\n");
      out.write("// Accordions\r\n");
      out.write("function myAccFunc(id) {\r\n");
      out.write("  var x = document.getElementById(id);\r\n");
      out.write("  if (x.className.indexOf(\"w3-show\") == -1) {\r\n");
      out.write("    x.className += \" w3-show\";\r\n");
      out.write("  } else { \r\n");
      out.write("    x.className = x.className.replace(\" w3-show\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Slideshows\r\n");
      out.write("var slideIndex = 1;\r\n");
      out.write("\r\n");
      out.write("function plusDivs(n) {\r\n");
      out.write("  slideIndex = slideIndex + n;\r\n");
      out.write("  showDivs(slideIndex);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showDivs(n) {\r\n");
      out.write("  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("  if (n > x.length) {slideIndex = 1}    \r\n");
      out.write("  if (n < 1) {slideIndex = x.length} ;\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].style.display = \"none\";  \r\n");
      out.write("  }\r\n");
      out.write("  x[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("showDivs(1);\r\n");
      out.write("\r\n");
      out.write("// Progress Bars\r\n");
      out.write("function move() {\r\n");
      out.write("  var elem = document.getElementById(\"myBar\");   \r\n");
      out.write("  var width = 1;\r\n");
      out.write("  var id = setInterval(frame, 10);\r\n");
      out.write("  function frame() {\r\n");
      out.write("    if (width == 100) {\r\n");
      out.write("      clearInterval(id);\r\n");
      out.write("    } else {\r\n");
      out.write("      width++; \r\n");
      out.write("      elem.style.width = width + '%'; \r\n");
      out.write("      elem.innerHTML = width * 1  + '%';\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index2.jsp(71,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      // /index2.jsp(71,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index2.jsp(71,2) '${boardList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("  	<tr>\r\n");
            out.write("  		<td><a href=\"BoardDetail.bo?board_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_subject }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("  		<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("  	</tr>\r\n");
            out.write("  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
